<?xml version="1.0" encoding="UTF-8"?>

<project name="prestamos-y-creditos-sage" default="default" basedir=".">

    <description>
        Builds, tests, and runs the project prestamos-y-creditos-sage.
    </description>

    <import file="nbproject/build-impl.xml"/>

    <target name="-post-compile">
        <echo message="Copiando recursos desde src/resources..."/>

        <copy todir="${build.classes.dir}" overwrite="true">
            <fileset dir="${basedir}/src/resources"
                     erroronmissingdir="false"/>
        </copy>
    </target>

</project>